### ISSUE TITLE
BE get heartbeat

### ISSUE THREAD

**Issue by bormilan** [Kalamansanai/plm-ssp#106]
need an endpoint for the client to get the heartbeat logs with a given detector id

**Comment by bormilan** [comment]
endoint uri: /api/v1/detectors/{id}/getheartbeat;

response is a list of the logs

**Comment by balint-szabox** [comment]
Heartbeat data displayed on the front end. It is not dynamically updated yet. It was arranged in one table. TimeStamp is built on the frontend.
Current looks of it:

![Image](https://user-images.githubusercontent.com/70958880/229292448-318bda23-783b-4c32-9159-a12284e4f830.png)
