### ISSUE TITLE
BE - logging

### ISSUE THREAD

**Issue by anguaive** [Kalamansanai/plm-ssp#26]
Logolasra hasznalhato a beepitett asp net core logger, vagy 3rd party logging konyvtarak, pl. Serilog. Ha 3rd partyt hasznalsz, a keretrendszer altal generalt log uzenetek (asp net core controller uzenetek, ef core DB muveletek logjai) a 3rd party loggerhez fognak kerulni, es nem a beepitett loggerhez. 

A Serilog logger kezelese sztem ergonomikusabb, ezert korabban azt hasznaltuk. 

Bekonfiguralhato, hogy a logger a konzolon kivul mashova is logoljon (pl. fajlba, OS logger szolgaltatasaba, halozaton keresztul vhova, stb.). Ez production kornyezetben lehet fontos. Ezeket nem kell kezzel megirni, altalaban be vannak epitve a loggerbe, esetleg egy kulon package-t le kell tolteni hozza.

At kell gondolni hogy mit erdemes logolni es mit nem. Pl. egy endpoint meghivasakor a handler fuggveny minden soranal logolni valoszinuleg felesleges.

**Comment by bormilan** [comment]
Serilog automatikusan belerakja a logs/SeriLogs.log fájlba a program logjait.
PlmLog pedig kézzel meghívva beleírja a logs/PlmLogs.log fájlba a kívánt üzenetet. Ez arra lehet jó, hogyha szeretnénk készíteni egy olyan logot, ahol csak specifikus dolgok logjait akarjuk látni. Ez azért jó, mert nincs tele minden szeméttel, átláthatóbban lehet követni a számunkra fontos dolgokat.
